spring:
  datasource:
#    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.97.97.208:3306/teacherGarden?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=CST
    username: root
    password: 1314525
