spring:
  datasource:
#    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://172.17.0.2:3306/teacherGarden?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=CST&allowMultiQueries=true
    username: root
    password: 123456
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml
server:
  servlet:
    context-path: /ssm_learning
  port: 8082
logging:
  file:
    path: D:/log

